#ifndef STATUS_H
#define STATUS_H

#define KERNEL16F_ALL_OK 0
#define KERNEL16F_FS_IO_ERROR 1
#define KERNEL16F_FS_FILE_NOT_FOUND_ERROR 2
#define KERNEL16F_FS_FILE_READ_ONLY_ERROR 3
#define KERNEL16F_FS_NOT_US 4
#define KERNEL16F_BAD_PATH 5
#define KERNEL16F_INVALID_DRIVE 6
#endif
